// client/src/App.jsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./api.js";
import { buildBasename, loadVersions, nextVersion, rememberVersion, stem } from "./naming.js";

function labelOf(profile, english) {
  return english ? profile?.profile?.en || profile?.profile?.fr : profile?.profile?.fr || "";
}

export default function App() {
  const [profiles, setProfiles] = useState([]);
  const [profileId, setProfileId] = useState("");
  const [english, setEnglish] = useState(false);
  const [company, setCompany] = useState("");
  const [version, setVersion] = useState(1);
  const [markdown, setMarkdown] = useState("");
  const [title, setTitle] = useState("");
  const [filename, setFilename] = useState("");
  const [filenameDirty, setFilenameDirty] = useState(false);
  const [status, setStatus] = useState("loading");
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState("");

  const selected = profiles.find((p) => p.id === profileId) || null;
  const heading = title || labelOf(selected, english) || "Profil";
  const autoStem = useMemo(
    () => stem({ title: heading, company, english }),
    [heading, company, english]
  );
  const autoName = useMemo(
    () => buildBasename({ title: heading, company, english }, version),
    [heading, company, english, version]
  );

  const showToast = useCallback((msg) => {
    setToast(msg);
    window.clearTimeout(showToast._t);
    showToast._t = window.setTimeout(() => setToast(""), 2800);
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const items = await api.profiles();
        if (cancelled) return;
        setProfiles(items);
        setProfileId(items[0]?.id || "");
        setStatus("ok");
      } catch (err) {
        if (!cancelled) {
          setStatus("error");
          showToast(err.message || "Chargement impossible");
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [showToast]);

  useEffect(() => {
    if (!profileId) return;
    let cancelled = false;
    setStatus("loading");
    (async () => {
      try {
        const data = await api.profile(profileId, english ? "en" : "fr");
        if (cancelled) return;
        setTitle(data.title || "");
        setMarkdown(data.markdown || "");
        setFilenameDirty(false);
        setStatus("ok");
      } catch (err) {
        if (!cancelled) {
          setStatus("error");
          showToast(err.message || "Profil introuvable");
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [profileId, english, showToast]);

  useEffect(() => {
    setVersion(nextVersion(autoStem, loadVersions()));
  }, [autoStem]);

  useEffect(() => {
    if (!filenameDirty) setFilename(autoName);
  }, [autoName, filenameDirty]);

  async function downloadPdf() {
    if (!markdown.trim()) return;
    setBusy(true);
    try {
      const res = await api.exportPdf(markdown, filename || autoName);
      const blob = await res.blob();
      const href = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = href;
      a.download = `${filename || autoName}.pdf`;
      a.click();
      URL.revokeObjectURL(href);
      rememberVersion(autoStem, version);
      setVersion(nextVersion(autoStem, loadVersions()));
      setFilenameDirty(false);
      showToast("PDF exporté (1 page)");
    } catch (err) {
      showToast(err.message || "Export impossible");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand">
          <img src="/favicon.ico" alt="" className="brand-logo" width="32" height="32" />
          <h1>CV</h1>
        </div>
        <label className="checkbox">
          <input
            type="checkbox"
            checked={english}
            disabled={busy}
            onChange={(e) => setEnglish(e.target.checked)}
          />
          English
        </label>
      </header>

      <section className="panel section-profiles">
        <div className="profile-bar">
          <h2>{heading}</h2>
          <div className="profile-select-wrap">
            <span
              className={`status-dot ${status}`}
              title={status === "ok" ? "Profil chargé" : status === "loading" ? "Chargement" : "Erreur"}
            />
            <select
              className="profile-select"
              value={profileId}
              disabled={busy || !profiles.length}
              onChange={(e) => setProfileId(e.target.value)}
            >
              {profiles.map((p) => (
                <option key={p.id} value={p.id}>
                  {labelOf(p, english)}
                </option>
              ))}
            </select>
          </div>
        </div>
      </section>

      <section className="panel editor-card">
        <div className="editor-col-head">
          <h2 className="editor-col-title">Markdown</h2>
          <label className="filename-field">
            <span className="sr-only">Nom du fichier</span>
            <input
              className="filename-input"
              spellCheck="false"
              value={filename}
              placeholder="lucas-schrever-…"
              onChange={(e) => {
                setFilenameDirty(true);
                setFilename(e.target.value);
              }}
            />
          </label>
        </div>
        <div className="meta-row">
          <label>
            Société
            <input
              value={company}
              disabled={busy}
              placeholder="defaut si vide"
              onChange={(e) => setCompany(e.target.value)}
            />
          </label>
          <label className="version-field">
            Version
            <input
              type="number"
              min="1"
              value={version}
              disabled={busy}
              onChange={(e) => {
                setVersion(Math.max(1, Number(e.target.value) || 1));
                setFilenameDirty(false);
              }}
            />
          </label>
        </div>
        <textarea
          className="editor-field preview"
          rows={18}
          spellCheck="false"
          disabled={busy}
          value={markdown}
          onChange={(e) => setMarkdown(e.target.value)}
          placeholder="Markdown du CV"
        />
        <button type="button" className="btn-export" disabled={!markdown.trim() || busy} onClick={downloadPdf}>
          {busy ? "Export…" : "Exporter le PDF"}
        </button>
      </section>

      {toast ? <div className="toast">{toast}</div> : null}
    </div>
  );
}

// client/src/App.vue
<script setup>
import { useCvApp } from "./composables/useCvApp.js";

const {
  profiles,
  selectedProfileId,
  headingTitle,
  profileStatus,
  jobText,
  markdown,
  filename,
  useLlm,
  english,
  llmOk,
  llmLabel,
  isBusy,
  generating,
  progressPct,
  progressLabel,
  result,
  history,
  toastMsg,
  hasMarkdown,
  progressSteps,
  stepState,
  generate,
  onProfileSelect,
  onFilenameInput,
  openGeneration,
  deleteGeneration,
  purgeHistory,
  downloadPdf,
  loadHistory,
} = useCvApp();

const profileStatusLabel = {
  loading: "Chargement du profil",
  ok: "Profil chargé",
  error: "Échec du chargement du profil",
};
</script>

<template>
  <div class="app-shell">
    <header class="topbar">
      <div class="brand">
        <img src="/favicon.ico" alt="" class="brand-logo" width="32" height="32" />
        <div>
          <h1>CV Generator</h1>
        </div>
      </div>
      <div class="topbar-meta">
        <span class="llm-pill" :class="llmOk ? 'ok' : 'warn'">{{ llmLabel }}</span>
      </div>
    </header>

    <section class="panel section-profiles">
      <div class="profile-bar">
        <h2>1. {{ headingTitle }}</h2>
        <div class="profile-select-wrap">
          <span
            class="status-dot"
            :class="profileStatus"
            :title="profileStatusLabel[profileStatus]"
            :aria-label="profileStatusLabel[profileStatus]"
          ></span>
          <select
            id="profile-select"
            class="profile-select"
            v-model.number="selectedProfileId"
            :disabled="isBusy"
            @change="onProfileSelect"
          >
            <option v-for="p in profiles" :key="p.id" :value="p.id">
              {{ p.name }}
            </option>
          </select>
        </div>
      </div>
    </section>

    <div class="editors-grid">
      <section class="panel editor-card">
        <h2 class="editor-col-title">2. Offre d'emploi</h2>
        <textarea
          v-model="jobText"
          class="editor-field"
          rows="14"
          :disabled="isBusy"
          placeholder="Colle l'offre (intitulé, employeur, missions, stack…)"
        ></textarea>
        <div class="options-row">
          <label class="checkbox">
            <input v-model="useLlm" type="checkbox" :disabled="!llmOk || isBusy" />
            LLM
          </label>
          <label class="checkbox">
            <input v-model="english" type="checkbox" :disabled="isBusy" />
            En anglais
          </label>
        </div>
        <button type="button" class="btn-generate" :disabled="isBusy" @click="generate">
          {{ generating ? "Adaptation en cours…" : "Adapter le CV" }}
        </button>
      </section>

      <section class="panel editor-card">
        <div class="editor-col-head">
          <h2 class="editor-col-title">Markdown rendu</h2>
          <label class="filename-field">
            <span class="sr-only">Nom du fichier</span>
            <input
              v-model="filename"
              class="filename-input"
              spellcheck="false"
              placeholder="lucas-schrever-…"
              @input="onFilenameInput"
            />
          </label>
        </div>
        <textarea
          v-model="markdown"
          class="editor-field preview"
          :class="{ 'mode-adapted': result }"
          rows="14"
          spellcheck="false"
          :disabled="isBusy"
          placeholder="Markdown du CV - modifiable avant export…"
        ></textarea>
        <button type="button" class="btn-export" :disabled="!hasMarkdown || isBusy" @click="downloadPdf">
          Exporter le PDF
        </button>
      </section>
    </div>

    <section class="panel section-loader" aria-live="polite">
      <div class="panel-head">
        <h2>Chargement</h2>
      </div>
      <div class="gen-progress">
        <div class="gen-progress-head">
          <span>{{ isBusy ? progressLabel : "Prêt" }}</span>
          <strong>{{ generating ? Math.round(progressPct) + "%" : isBusy ? "…" : "-" }}</strong>
        </div>
        <div
          class="gen-progress-track"
          role="progressbar"
          aria-valuemin="0"
          aria-valuemax="100"
          :aria-valuenow="generating ? Math.round(progressPct) : isBusy ? undefined : 0"
          :aria-busy="isBusy"
        >
          <div
            class="gen-progress-bar"
            :class="{ idle: !isBusy, indeterminate: isBusy && !generating }"
            :style="{ width: (generating ? Math.round(progressPct) : 0) + '%' }"
          ></div>
        </div>
        <ol class="gen-steps">
          <li v-for="step in progressSteps" :key="step.id" :class="stepState(step.id)">
            {{ step.label }}
          </li>
        </ol>
      </div>
      <ul v-if="result?.warnings?.length" class="warnings">
        <li v-for="(w, i) in result.warnings" :key="i">{{ w }}</li>
      </ul>
    </section>

    <section class="panel section-history">
      <div class="panel-head spread">
        <h2>Historique</h2>
        <div class="row">
          <button type="button" class="secondary small danger-text" :disabled="isBusy" @click="purgeHistory">
            Vider
          </button>
          <button type="button" class="secondary small" :disabled="isBusy" @click="loadHistory">Rafraîchir</button>
        </div>
      </div>
      <ul class="history">
        <li v-if="!history.length" class="muted">Aucune génération.</li>
        <li v-for="g in history" :key="g.id">
          <div class="history-main">
            <button type="button" class="history-open" :disabled="isBusy" @click="openGeneration(g.id)">
              {{ g.title }}
            </button>
            <div class="date">{{ new Date(g.created_at).toLocaleString("fr-FR") }}</div>
          </div>
          <div class="history-actions">
            <button
              type="button"
              class="btn-icon danger"
              title="Supprimer"
              :disabled="isBusy"
              @click="deleteGeneration(g.id)"
            >
              ✕
            </button>
          </div>
        </li>
      </ul>
    </section>

    <div v-if="toastMsg" class="toast">{{ toastMsg }}</div>
  </div>
</template>
