// client/src/App.vue
<script setup>
import { ref, watch, onMounted } from 'vue'
import {
  pingApi,
  fetchCategories,
  fetchProfiles,
  fetchProfile,
  fetchDefaultProfile,
  deleteProfile,
  analyzeJob,
  exportPdf,
  fetchOllamaStatus,
} from './api/http.js'
import { loadUiState, saveUiState } from './storage.js'

const saved = loadUiState()
const english = ref(saved.english)
const search = ref('')
const category = ref('')
const categories = ref([])
const profiles = ref([])
const selectedId = ref(saved.selectedId)
const jobText = ref(saved.jobText)
const cvMarkdown = ref(saved.cvMarkdown)
const exportFilename = ref(saved.exportFilename)
const loadingList = ref(false)
const loadingProfile = ref(false)
const analyzing = ref(false)
const pdfLoading = ref(false)
const ollamaStatus = ref('Ollama : …')
const ollamaState = ref('checking')
const ollamaReady = ref(false)
const toast = ref('')
let toastTimer = null
let searchTimer = null
let persistReady = false

function showToast(msg) {
  toast.value = msg
  clearTimeout(toastTimer)
  toastTimer = setTimeout(() => { toast.value = '' }, 3600)
}

function persist() {
  if (!persistReady) return
  saveUiState({
    jobText: jobText.value,
    cvMarkdown: cvMarkdown.value,
    selectedId: selectedId.value,
    exportFilename: exportFilename.value,
    english: english.value,
  })
}

async function checkOllama() {
  ollamaState.value = 'checking'
  ollamaStatus.value = 'Ollama : vérification…'
  try {
    const data = await fetchOllamaStatus()
    ollamaReady.value = Boolean(data.server_ok && data.model_ready && data.enabled)
    ollamaStatus.value = data.message
    ollamaState.value = ollamaReady.value ? 'ok' : 'error'
  } catch (e) {
    ollamaReady.value = false
    ollamaStatus.value = e.message || 'Ollama indisponible'
    ollamaState.value = 'error'
  }
}

async function loadCategories() {
  const data = await fetchCategories()
  categories.value = data.items || []
}

async function loadProfiles() {
  loadingList.value = true
  try {
    const data = await fetchProfiles({
      q: search.value.trim(),
      category: category.value,
    })
    profiles.value = data.items || []
  } catch (e) {
    profiles.value = []
    showToast(e.message || 'Chargement profils impossible.')
  } finally {
    loadingList.value = false
  }
}

function scheduleSearch() {
  loadingList.value = true
  clearTimeout(searchTimer)
  searchTimer = setTimeout(loadProfiles, 300)
}

async function openProfile(id, { silent = false } = {}) {
  if (loadingProfile.value) return
  loadingProfile.value = true
  try {
    const data = await fetchProfile(id, { english: english.value })
    selectedId.value = data.id
    cvMarkdown.value = data.markdown || ''
    exportFilename.value = data.filename || 'cv'
    if (!silent) showToast(`Profil chargé : ${data.name}`)
  } catch (e) {
    showToast(e.message || 'Impossible de charger le profil.')
  } finally {
    loadingProfile.value = false
  }
}

async function loadDefault() {
  if (loadingProfile.value) return
  loadingProfile.value = true
  try {
    const data = await fetchDefaultProfile({ english: english.value })
    selectedId.value = data.id
    cvMarkdown.value = data.markdown || ''
    exportFilename.value = data.filename || 'cv-lucas-schrever-dotnet-react'
    showToast(`Profil défaut : ${data.name}`)
  } catch (e) {
    showToast(e.message || 'Pas de profil par défaut.')
  } finally {
    loadingProfile.value = false
  }
}

async function restoreSession() {
  if (selectedId.value && cvMarkdown.value.trim()) {
    const stillThere = profiles.value.some((p) => p.id === selectedId.value)
    if (!stillThere) {
      try {
        await fetchProfile(selectedId.value)
      } catch {
        selectedId.value = null
        cvMarkdown.value = ''
        exportFilename.value = 'cv'
        await loadDefault()
        return
      }
    }
    showToast('Session restaurée')
    return
  }
  if (selectedId.value) {
    await openProfile(selectedId.value, { silent: true })
    return
  }
  await loadDefault()
}

async function onDelete(profile) {
  if (profile.is_default) {
    showToast('Le profil par défaut ne peut pas être supprimé.')
    return
  }
  const ok = window.confirm(`Supprimer le profil « ${profile.name} » ?`)
  if (!ok) return
  try {
    await deleteProfile(profile.id)
    if (selectedId.value === profile.id) {
      selectedId.value = null
      cvMarkdown.value = ''
      exportFilename.value = 'cv'
    }
    showToast('Profil supprimé.')
    await loadProfiles()
  } catch (e) {
    showToast(e.message || 'Suppression impossible.')
  }
}

async function onAnalyze() {
  const text = jobText.value.trim()
  if (text.length < 10) {
    showToast('Colle une offre (min. 10 caractères).')
    return
  }
  analyzing.value = true
  try {
    const result = await analyzeJob({
      job_text: text,
      profile_id: selectedId.value || undefined,
      english: english.value,
    })
    if (!result.profile) {
      showToast(result.message || 'Adaptation impossible.')
      return
    }
    selectedId.value = result.profile.id
    cvMarkdown.value = result.profile.markdown || ''
    exportFilename.value = result.profile.filename || 'cv'
    const parts = [result.message || 'Profil adapté']
    if (result.profile.title) parts.push(`titre : ${result.profile.title}`)
    if (result.company) parts.push(result.company)
    if (result.reason) parts.push(result.reason)
    if (result.fallback) parts.push('fallback local')
    showToast(parts.join(' · '))
  } catch (e) {
    showToast(e.message || 'Adaptation impossible.')
  } finally {
    analyzing.value = false
  }
}

async function onExportPdf() {
  if (!cvMarkdown.value.trim()) {
    showToast('Rien à exporter.')
    return
  }
  pdfLoading.value = true
  try {
    const { blob, filename } = await exportPdf({
      markdown: cvMarkdown.value,
      filename: exportFilename.value,
    })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = filename
    a.click()
    URL.revokeObjectURL(a.href)
    showToast(`PDF téléchargé — ${filename}`)
  } catch (e) {
    showToast(e.message || 'PDF indisponible.')
  } finally {
    pdfLoading.value = false
  }
}

watch(english, async (val, oldVal) => {
  if (val === oldVal) return
  persist()
  if (selectedId.value) {
    await openProfile(selectedId.value)
  }
})

watch(category, () => {
  loadingList.value = true
  loadProfiles()
})

watch([jobText, cvMarkdown, selectedId, exportFilename], () => {
  persist()
})

onMounted(async () => {
  try {
    await pingApi()
    await checkOllama()
    await loadCategories()
    await loadProfiles()
    await restoreSession()
  } catch (e) {
    showToast(e.message || 'Backend indisponible.')
  } finally {
    persistReady = true
    persist()
  }
})
</script>

<template>
  <div class="app-shell">
    <header class="topbar">
      <div class="brand">
        <div>
          <h1>CV Generator</h1>
          <p class="muted">Profils statiques → offre → adaptation → PDF</p>
        </div>
      </div>
      <div class="topbar-actions">
        <label class="checkbox" :class="{ disabled: loadingProfile }">
          <input v-model="english" type="checkbox" :disabled="loadingProfile || analyzing" />
          En anglais
        </label>
        <button
          type="button"
          class="btn-secondary"
          :disabled="loadingProfile"
          @click="loadDefault"
        >
          Profil défaut
        </button>
        <button
          type="button"
          class="ollama-pill"
          :class="`ollama-pill--${ollamaState}`"
          title="Cliquer pour revérifier"
          @click="checkOllama"
        >
          {{ ollamaStatus }}
        </button>
      </div>
    </header>

    <section class="panel panel-profiles">
      <div class="filters">
        <input
          v-model="search"
          class="search-input"
          type="search"
          placeholder="Rechercher un profil…"
          :disabled="loadingProfile"
          @input="scheduleSearch"
        />
        <select
          v-model="category"
          class="category-select"
          :disabled="loadingProfile"
        >
          <option value="">Toutes les catégories</option>
          <option v-for="c in categories" :key="c.id" :value="c.name">
            {{ c.label_fr }}
          </option>
        </select>
      </div>

      <div v-if="loadingList" class="inline-loader">
        <span class="spinner" />
        <span>Recherche…</span>
      </div>

      <ul v-if="profiles.length" class="profile-list" :class="{ dimmed: loadingList }">
        <li
          v-for="p in profiles"
          :key="p.id"
          :class="{ active: selectedId === p.id, default: p.is_default }"
        >
          <button
            type="button"
            class="profile-open"
            :disabled="loadingProfile"
            @click="openProfile(p.id)"
          >
            <span class="profile-name">
              {{ p.name }}
              <span v-if="p.is_default" class="badge">défaut</span>
            </span>
            <span class="profile-meta">{{ p.category?.label_fr }} · {{ p.title }}</span>
          </button>
          <button
            type="button"
            class="history-delete"
            title="Supprimer"
            :disabled="p.is_default || loadingProfile"
            @click="onDelete(p)"
          >
            ×
          </button>
        </li>
      </ul>
      <p v-else-if="loadingList" class="muted">Chargement…</p>
      <p v-else class="muted">Aucun profil.</p>
    </section>

    <div class="workspace">
      <section class="panel col-input">
        <h2>Fiche de poste</h2>
        <textarea
          v-model="jobText"
          class="editor-field"
          rows="14"
          placeholder="Colle l’offre : intitulé, missions, stack…"
          :disabled="analyzing"
        />
        <div v-if="analyzing" class="inline-loader">
          <span class="spinner" />
          <span>{{ ollamaReady ? 'Adaptation Ollama…' : 'Adaptation locale…' }}</span>
        </div>
        <button
          class="btn-action"
          type="button"
          :disabled="analyzing"
          @click="onAnalyze"
        >
          {{
            analyzing
              ? (ollamaReady ? 'Adaptation Ollama…' : 'Adaptation…')
              : 'Adapter le profil à l’offre'
          }}
        </button>
      </section>

      <section class="panel col-preview">
        <h2>CV</h2>
        <div class="cv-wrap" :class="{ loading: loadingProfile }">
          <div v-if="loadingProfile" class="cv-overlay">
            <span class="spinner spinner--dark" />
            <span>Chargement du profil…</span>
          </div>
          <textarea
            v-model="cvMarkdown"
            class="editor-field"
            spellcheck="false"
            placeholder="Markdown du CV…"
            :disabled="loadingProfile"
          />
        </div>
        <p v-if="exportFilename && cvMarkdown.trim()" class="export-name muted">
          Fichier : <strong>{{ exportFilename }}.pdf</strong>
        </p>
        <button
          class="btn-action"
          type="button"
          :disabled="pdfLoading || loadingProfile || !cvMarkdown.trim()"
          @click="onExportPdf"
        >
          {{ pdfLoading ? 'Export…' : 'Télécharger PDF' }}
        </button>
      </section>
    </div>

    <div v-if="toast" class="toast">{{ toast }}</div>
  </div>
</template>

// client/src/App.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { api } from "./api";
import { buildBasename } from "./naming";
import type { LoadStatus, ProfileSummary } from "./types";

function labelOf(profile: ProfileSummary | null | undefined, english: boolean): string {
  if (!profile?.profile) return "";
  return english ? profile.profile.en || profile.profile.fr || "" : profile.profile.fr || "";
}

function errMessage(err: unknown, fallback: string): string {
  return err instanceof Error && err.message ? err.message : fallback;
}

export default function App() {
  const [profiles, setProfiles] = useState<ProfileSummary[]>([]);
  const [profileId, setProfileId] = useState("");
  const [english, setEnglish] = useState(false);
  const [markdown, setMarkdown] = useState("");
  const [title, setTitle] = useState("");
  const [filename, setFilename] = useState("");
  const [filenameDirty, setFilenameDirty] = useState(false);
  const [status, setStatus] = useState<LoadStatus>("loading");
  const [busy, setBusy] = useState(false);
  const [translating, setTranslating] = useState(false);
  const [toast, setToast] = useState("");
  const toastTimer = useRef<number | undefined>(undefined);

  const selected = profiles.find((p) => p.id === profileId) || null;
  const heading = title || labelOf(selected, english) || "Profil";
  const autoName = useMemo(
    () => buildBasename({ title: heading, english }),
    [heading, english]
  );

  const showToast = useCallback((msg: string) => {
    setToast(msg);
    window.clearTimeout(toastTimer.current);
    toastTimer.current = window.setTimeout(() => setToast(""), 2800);
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const items = await api.profiles();
        if (cancelled) return;
        setProfiles(items);
        setProfileId(items[0]?.id || "");
        setStatus("ok");
      } catch (err) {
        if (!cancelled) {
          setStatus("error");
          showToast(errMessage(err, "Chargement impossible"));
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [showToast]);

  useEffect(() => {
    if (!profileId) return;
    let cancelled = false;
    setStatus("loading");
    (async () => {
      try {
        const data = await api.profile(profileId, english ? "en" : "fr");
        if (cancelled) return;
        setTitle(data.title || "");
        setMarkdown(data.markdown || "");
        setFilenameDirty(false);
        setStatus("ok");
      } catch (err) {
        if (!cancelled) {
          setStatus("error");
          showToast(errMessage(err, "Profil introuvable"));
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [profileId, english, showToast]);

  useEffect(() => {
    if (!filenameDirty) setFilename(autoName);
  }, [autoName, filenameDirty]);

  async function downloadPdf() {
    if (!markdown.trim()) return;
    setBusy(true);
    try {
      const res = await api.exportPdf(markdown, filename || autoName);
      const blob = await res.blob();
      const href = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = href;
      a.download = `${filename || autoName}.pdf`;
      a.click();
      URL.revokeObjectURL(href);
      setFilenameDirty(false);
      showToast("PDF exporté (1 page)");
    } catch (err) {
      showToast(errMessage(err, "Export impossible"));
    } finally {
      setBusy(false);
    }
  }

  async function applyDefault() {
    if (!profileId || !markdown.trim()) return;
    setBusy(true);
    setTranslating(true);
    try {
      const result = await api.applyDefault(profileId, markdown, english ? "en" : "fr");
      if (result.translated) {
        showToast("Défaut enregistré, autre langue traduite");
      } else {
        showToast(result.error || "Défaut enregistré (traduction indisponible)");
      }
    } catch (err) {
      showToast(errMessage(err, "Enregistrement impossible"));
    } finally {
      setTranslating(false);
      setBusy(false);
    }
  }

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand">
          <img src="/favicon.ico" alt="" className="brand-logo" width={32} height={32} />
          <h1>CV</h1>
        </div>
        <label className="checkbox">
          <input
            type="checkbox"
            checked={english}
            disabled={busy}
            onChange={(e) => setEnglish(e.target.checked)}
          />
          English
        </label>
      </header>

      <section className="panel section-profiles">
        <div className="profile-bar">
          <h2>{heading}</h2>
          <div className="profile-select-wrap">
            <span
              className={`status-dot ${status}`}
              title={status === "ok" ? "Profil chargé" : status === "loading" ? "Chargement" : "Erreur"}
            />
            <select
              className="profile-select"
              value={profileId}
              disabled={busy || !profiles.length}
              onChange={(e) => setProfileId(e.target.value)}
            >
              {profiles.map((p) => (
                <option key={p.id} value={p.id}>
                  {labelOf(p, english)}
                </option>
              ))}
            </select>
          </div>
        </div>
      </section>

      <section className="panel editor-card">
        <div className="editor-col-head">
          <h2 className="editor-col-title">Markdown</h2>
          <label className="filename-field">
            <span className="sr-only">Nom du fichier</span>
            <input
              className="filename-input"
              spellCheck={false}
              value={filename}
              placeholder="lucas-schrever-…"
              onChange={(e) => {
                setFilenameDirty(true);
                setFilename(e.target.value);
              }}
            />
          </label>
        </div>
        <textarea
          className="editor-field preview"
          rows={18}
          spellCheck={false}
          disabled={busy}
          value={markdown}
          onChange={(e) => setMarkdown(e.target.value)}
          placeholder="Markdown du CV"
        />
        <div className="editor-actions">
          <button
            type="button"
            className="btn-default"
            disabled={!profileId || !markdown.trim() || busy}
            onClick={applyDefault}
          >
            {translating ? "Traduction…" : "Appliquer défaut"}
          </button>
          <button type="button" className="btn-export" disabled={!markdown.trim() || busy} onClick={downloadPdf}>
            {busy && !translating ? "Export…" : "Exporter le PDF"}
          </button>
        </div>
      </section>

      {toast ? <div className="toast">{toast}</div> : null}
    </div>
  );
}
